--Generated By msgid-gen-lua Do not Edit
local config = {
    QueryGateArg = 9179,    ----授权协议
    LoginChallenge = 58495, ----连接游戏服务器，服务器返回
    ErrorInfo = 21940,      ----服务器发的错误消息
    LoginArg = 10091,       ----登录
    LoginRes = 10091,       ----登录返回
    SelectRoleNew = 217,    ----选角色消息
    IBGiftIcon = 44659,
    CreateRoleNew = 13034,   ----创建角色消息
    SelectRoleNtfData = 19493,
    NotifyStartUpTypeToClient = 64412,
    KeepAlivePingAck = 29192 ,   --keepAliveAck  心跳包，服务器定时下发的，暂时只在hallconnector的收数据逻辑里做了判断，没有给服务器返回
    SceneCfg = 63366,               ---进入游戏时，接收到这个消息进入场景
    Systems = 41168,            ---哪些系统开
    ChatNotify = 4256,           ---聊天消息
    WorldChannelLeftTimesNtf = 37503 ,---聊天 功能模块里的，
    
    GetClassifyDesignation=40256,----请求称号列表
    SpriteOperation=62961,
    SpriteChanged=197,
    ItemChanged=20270,


    
    DoEnterSceneArg = 45201,---进场景前发
    DoEnterSceneRes = 45201,


    IBBuyItem=11547  --购买物品
}
return config
