-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ABSPARTYBASE_PB = require("AbsPartyBase_pb")
module('AbsPartyInfo_pb')


ABSPARTYINFO = protobuf.Descriptor();
local ABSPARTYINFO_ABY_FIELD = protobuf.FieldDescriptor();
local ABSPARTYINFO_ABYSSMAILTIME_FIELD = protobuf.FieldDescriptor();

ABSPARTYINFO_ABY_FIELD.name = "aby"
ABSPARTYINFO_ABY_FIELD.full_name = ".KKSG.AbsPartyInfo.aby"
ABSPARTYINFO_ABY_FIELD.number = 1
ABSPARTYINFO_ABY_FIELD.index = 0
ABSPARTYINFO_ABY_FIELD.label = 3
ABSPARTYINFO_ABY_FIELD.has_default_value = false
ABSPARTYINFO_ABY_FIELD.default_value = {}
ABSPARTYINFO_ABY_FIELD.message_type = ABSPARTYBASE_PB.ABSPARTYBASE
ABSPARTYINFO_ABY_FIELD.type = 11
ABSPARTYINFO_ABY_FIELD.cpp_type = 10

ABSPARTYINFO_ABYSSMAILTIME_FIELD.name = "abyssmailtime"
ABSPARTYINFO_ABYSSMAILTIME_FIELD.full_name = ".KKSG.AbsPartyInfo.abyssmailtime"
ABSPARTYINFO_ABYSSMAILTIME_FIELD.number = 2
ABSPARTYINFO_ABYSSMAILTIME_FIELD.index = 1
ABSPARTYINFO_ABYSSMAILTIME_FIELD.label = 1
ABSPARTYINFO_ABYSSMAILTIME_FIELD.has_default_value = false
ABSPARTYINFO_ABYSSMAILTIME_FIELD.default_value = 0
ABSPARTYINFO_ABYSSMAILTIME_FIELD.type = 13
ABSPARTYINFO_ABYSSMAILTIME_FIELD.cpp_type = 3

ABSPARTYINFO.name = "AbsPartyInfo"
ABSPARTYINFO.full_name = ".KKSG.AbsPartyInfo"
ABSPARTYINFO.nested_types = {}
ABSPARTYINFO.enum_types = {}
ABSPARTYINFO.fields = {ABSPARTYINFO_ABY_FIELD, ABSPARTYINFO_ABYSSMAILTIME_FIELD}
ABSPARTYINFO.is_extendable = false
ABSPARTYINFO.extensions = {}

AbsPartyInfo = protobuf.Message(ABSPARTYINFO)

