-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('AncientTimes_pb')


ANCIENTTIMES = protobuf.Descriptor();
local ANCIENTTIMES_AWARD_FIELD = protobuf.FieldDescriptor();

ANCIENTTIMES_AWARD_FIELD.name = "award"
ANCIENTTIMES_AWARD_FIELD.full_name = ".KKSG.AncientTimes.award"
ANCIENTTIMES_AWARD_FIELD.number = 1
ANCIENTTIMES_AWARD_FIELD.index = 0
ANCIENTTIMES_AWARD_FIELD.label = 1
ANCIENTTIMES_AWARD_FIELD.has_default_value = false
ANCIENTTIMES_AWARD_FIELD.default_value = 0
ANCIENTTIMES_AWARD_FIELD.type = 13
ANCIENTTIMES_AWARD_FIELD.cpp_type = 3

ANCIENTTIMES.name = "AncientTimes"
ANCIENTTIMES.full_name = ".KKSG.AncientTimes"
ANCIENTTIMES.nested_types = {}
ANCIENTTIMES.enum_types = {}
ANCIENTTIMES.fields = {ANCIENTTIMES_AWARD_FIELD}
ANCIENTTIMES.is_extendable = false
ANCIENTTIMES.extensions = {}

AncientTimes = protobuf.Message(ANCIENTTIMES)

