-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local LONGZHIGU_PB = require("longzhigu_pb")
local ROLEBRIEFINFO_PB = require("RoleBriefInfo_pb")
module('BackFlowBuy_pb')


BACKFLOWBUY = protobuf.Descriptor();
local BACKFLOWBUY_INDEX_FIELD = protobuf.FieldDescriptor();
local BACKFLOWBUY_DAY_FIELD = protobuf.FieldDescriptor();
local BACKFLOWBUY_COUNT_FIELD = protobuf.FieldDescriptor();

BACKFLOWBUY_INDEX_FIELD.name = "index"
BACKFLOWBUY_INDEX_FIELD.full_name = ".KKSG.BackFlowBuy.index"
BACKFLOWBUY_INDEX_FIELD.number = 1
BACKFLOWBUY_INDEX_FIELD.index = 0
BACKFLOWBUY_INDEX_FIELD.label = 1
BACKFLOWBUY_INDEX_FIELD.has_default_value = false
BACKFLOWBUY_INDEX_FIELD.default_value = 0
BACKFLOWBUY_INDEX_FIELD.type = 13
BACKFLOWBUY_INDEX_FIELD.cpp_type = 3

BACKFLOWBUY_DAY_FIELD.name = "day"
BACKFLOWBUY_DAY_FIELD.full_name = ".KKSG.BackFlowBuy.day"
BACKFLOWBUY_DAY_FIELD.number = 2
BACKFLOWBUY_DAY_FIELD.index = 1
BACKFLOWBUY_DAY_FIELD.label = 1
BACKFLOWBUY_DAY_FIELD.has_default_value = false
BACKFLOWBUY_DAY_FIELD.default_value = 0
BACKFLOWBUY_DAY_FIELD.type = 13
BACKFLOWBUY_DAY_FIELD.cpp_type = 3

BACKFLOWBUY_COUNT_FIELD.name = "count"
BACKFLOWBUY_COUNT_FIELD.full_name = ".KKSG.BackFlowBuy.count"
BACKFLOWBUY_COUNT_FIELD.number = 3
BACKFLOWBUY_COUNT_FIELD.index = 2
BACKFLOWBUY_COUNT_FIELD.label = 1
BACKFLOWBUY_COUNT_FIELD.has_default_value = false
BACKFLOWBUY_COUNT_FIELD.default_value = 0
BACKFLOWBUY_COUNT_FIELD.type = 13
BACKFLOWBUY_COUNT_FIELD.cpp_type = 3

BACKFLOWBUY.name = "BackFlowBuy"
BACKFLOWBUY.full_name = ".KKSG.BackFlowBuy"
BACKFLOWBUY.nested_types = {}
BACKFLOWBUY.enum_types = {}
BACKFLOWBUY.fields = {BACKFLOWBUY_INDEX_FIELD, BACKFLOWBUY_DAY_FIELD, BACKFLOWBUY_COUNT_FIELD}
BACKFLOWBUY.is_extendable = false
BACKFLOWBUY.extensions = {}

BackFlowBuy = protobuf.Message(BACKFLOWBUY)

