-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local BAGTYPE_PB = require("BagType_pb")
module('BagExpandData_pb')


BAGEXPANDDATA = protobuf.Descriptor();
local BAGEXPANDDATA_TYPE_FIELD = protobuf.FieldDescriptor();
local BAGEXPANDDATA_NUM_FIELD = protobuf.FieldDescriptor();
local BAGEXPANDDATA_COUNT_FIELD = protobuf.FieldDescriptor();

BAGEXPANDDATA_TYPE_FIELD.name = "type"
BAGEXPANDDATA_TYPE_FIELD.full_name = ".KKSG.BagExpandData.type"
BAGEXPANDDATA_TYPE_FIELD.number = 1
BAGEXPANDDATA_TYPE_FIELD.index = 0
BAGEXPANDDATA_TYPE_FIELD.label = 1
BAGEXPANDDATA_TYPE_FIELD.has_default_value = false
BAGEXPANDDATA_TYPE_FIELD.default_value = nil
BAGEXPANDDATA_TYPE_FIELD.enum_type = BAGTYPE_PB.BAGTYPE
BAGEXPANDDATA_TYPE_FIELD.type = 14
BAGEXPANDDATA_TYPE_FIELD.cpp_type = 8

BAGEXPANDDATA_NUM_FIELD.name = "num"
BAGEXPANDDATA_NUM_FIELD.full_name = ".KKSG.BagExpandData.num"
BAGEXPANDDATA_NUM_FIELD.number = 2
BAGEXPANDDATA_NUM_FIELD.index = 1
BAGEXPANDDATA_NUM_FIELD.label = 1
BAGEXPANDDATA_NUM_FIELD.has_default_value = false
BAGEXPANDDATA_NUM_FIELD.default_value = 0
BAGEXPANDDATA_NUM_FIELD.type = 13
BAGEXPANDDATA_NUM_FIELD.cpp_type = 3

BAGEXPANDDATA_COUNT_FIELD.name = "count"
BAGEXPANDDATA_COUNT_FIELD.full_name = ".KKSG.BagExpandData.count"
BAGEXPANDDATA_COUNT_FIELD.number = 3
BAGEXPANDDATA_COUNT_FIELD.index = 2
BAGEXPANDDATA_COUNT_FIELD.label = 1
BAGEXPANDDATA_COUNT_FIELD.has_default_value = false
BAGEXPANDDATA_COUNT_FIELD.default_value = 0
BAGEXPANDDATA_COUNT_FIELD.type = 13
BAGEXPANDDATA_COUNT_FIELD.cpp_type = 3

BAGEXPANDDATA.name = "BagExpandData"
BAGEXPANDDATA.full_name = ".KKSG.BagExpandData"
BAGEXPANDDATA.nested_types = {}
BAGEXPANDDATA.enum_types = {}
BAGEXPANDDATA.fields = {BAGEXPANDDATA_TYPE_FIELD, BAGEXPANDDATA_NUM_FIELD, BAGEXPANDDATA_COUNT_FIELD}
BAGEXPANDDATA.is_extendable = false
BAGEXPANDDATA.extensions = {}

BagExpandData = protobuf.Message(BAGEXPANDDATA)

