-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('BagType_pb')


local BAGTYPE = protobuf.EnumDescriptor();
local BAGTYPE_EQUIPBAG_ENUM = protobuf.EnumValueDescriptor();
local BAGTYPE_EMBLEMBAG_ENUM = protobuf.EnumValueDescriptor();
local BAGTYPE_ARTIFACTBAG_ENUM = protobuf.EnumValueDescriptor();
local BAGTYPE_ITEMBAG_ENUM = protobuf.EnumValueDescriptor();

BAGTYPE_EQUIPBAG_ENUM.name = "EquipBag"
BAGTYPE_EQUIPBAG_ENUM.index = 0
BAGTYPE_EQUIPBAG_ENUM.number = 1
BAGTYPE_EMBLEMBAG_ENUM.name = "EmblemBag"
BAGTYPE_EMBLEMBAG_ENUM.index = 1
BAGTYPE_EMBLEMBAG_ENUM.number = 2
BAGTYPE_ARTIFACTBAG_ENUM.name = "ArtifactBag"
BAGTYPE_ARTIFACTBAG_ENUM.index = 2
BAGTYPE_ARTIFACTBAG_ENUM.number = 3
BAGTYPE_ITEMBAG_ENUM.name = "ItemBag"
BAGTYPE_ITEMBAG_ENUM.index = 3
BAGTYPE_ITEMBAG_ENUM.number = 4
BAGTYPE.name = "BagType"
BAGTYPE.full_name = ".KKSG.BagType"
BAGTYPE.values = {BAGTYPE_EQUIPBAG_ENUM,BAGTYPE_EMBLEMBAG_ENUM,BAGTYPE_ARTIFACTBAG_ENUM,BAGTYPE_ITEMBAG_ENUM}

ArtifactBag = 3
EmblemBag = 2
EquipBag = 1
ItemBag = 4

