-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('BlackListReport_pb')


BLACKLISTREPORT = protobuf.Descriptor();

BLACKLISTREPORT.name = "BlackListReport"
BLACKLISTREPORT.full_name = ".KKSG.BlackListReport"
BLACKLISTREPORT.nested_types = {}
BLACKLISTREPORT.enum_types = {}
BLACKLISTREPORT.fields = {}
BLACKLISTREPORT.is_extendable = false
BLACKLISTREPORT.extensions = {}

BlackListReport = protobuf.Message(BLACKLISTREPORT)

