-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local BOSSRUSHREQSTATUS_PB = require("BossRushReqStatus_pb")
module('BossRushArg_pb')


BOSSRUSHARG = protobuf.Descriptor();
local BOSSRUSHARG_TYPE_FIELD = protobuf.FieldDescriptor();

BOSSRUSHARG_TYPE_FIELD.name = "type"
BOSSRUSHARG_TYPE_FIELD.full_name = ".KKSG.BossRushArg.type"
BOSSRUSHARG_TYPE_FIELD.number = 1
BOSSRUSHARG_TYPE_FIELD.index = 0
BOSSRUSHARG_TYPE_FIELD.label = 1
BOSSRUSHARG_TYPE_FIELD.has_default_value = false
BOSSRUSHARG_TYPE_FIELD.default_value = nil
BOSSRUSHARG_TYPE_FIELD.enum_type = BOSSRUSHREQSTATUS_PB.BOSSRUSHREQSTATUS
BOSSRUSHARG_TYPE_FIELD.type = 14
BOSSRUSHARG_TYPE_FIELD.cpp_type = 8

BOSSRUSHARG.name = "BossRushArg"
BOSSRUSHARG.full_name = ".KKSG.BossRushArg"
BOSSRUSHARG.nested_types = {}
BOSSRUSHARG.enum_types = {}
BOSSRUSHARG.fields = {BOSSRUSHARG_TYPE_FIELD}
BOSSRUSHARG.is_extendable = false
BOSSRUSHARG.extensions = {}

BossRushArg = protobuf.Message(BOSSRUSHARG)

