-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('BuffItem_pb')


BUFFITEM = protobuf.Descriptor();
local BUFFITEM_ITEMID_FIELD = protobuf.FieldDescriptor();
local BUFFITEM_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
local BUFFITEM_EXPIRETIME_FIELD = protobuf.FieldDescriptor();

BUFFITEM_ITEMID_FIELD.name = "itemid"
BUFFITEM_ITEMID_FIELD.full_name = ".KKSG.BuffItem.itemid"
BUFFITEM_ITEMID_FIELD.number = 1
BUFFITEM_ITEMID_FIELD.index = 0
BUFFITEM_ITEMID_FIELD.label = 1
BUFFITEM_ITEMID_FIELD.has_default_value = false
BUFFITEM_ITEMID_FIELD.default_value = 0
BUFFITEM_ITEMID_FIELD.type = 13
BUFFITEM_ITEMID_FIELD.cpp_type = 3

BUFFITEM_ITEMCOUNT_FIELD.name = "itemcount"
BUFFITEM_ITEMCOUNT_FIELD.full_name = ".KKSG.BuffItem.itemcount"
BUFFITEM_ITEMCOUNT_FIELD.number = 2
BUFFITEM_ITEMCOUNT_FIELD.index = 1
BUFFITEM_ITEMCOUNT_FIELD.label = 1
BUFFITEM_ITEMCOUNT_FIELD.has_default_value = false
BUFFITEM_ITEMCOUNT_FIELD.default_value = 0
BUFFITEM_ITEMCOUNT_FIELD.type = 13
BUFFITEM_ITEMCOUNT_FIELD.cpp_type = 3

BUFFITEM_EXPIRETIME_FIELD.name = "expiretime"
BUFFITEM_EXPIRETIME_FIELD.full_name = ".KKSG.BuffItem.expiretime"
BUFFITEM_EXPIRETIME_FIELD.number = 3
BUFFITEM_EXPIRETIME_FIELD.index = 2
BUFFITEM_EXPIRETIME_FIELD.label = 1
BUFFITEM_EXPIRETIME_FIELD.has_default_value = false
BUFFITEM_EXPIRETIME_FIELD.default_value = 0
BUFFITEM_EXPIRETIME_FIELD.type = 13
BUFFITEM_EXPIRETIME_FIELD.cpp_type = 3

BUFFITEM.name = "BuffItem"
BUFFITEM.full_name = ".KKSG.BuffItem"
BUFFITEM.nested_types = {}
BUFFITEM.enum_types = {}
BUFFITEM.fields = {BUFFITEM_ITEMID_FIELD, BUFFITEM_ITEMCOUNT_FIELD, BUFFITEM_EXPIRETIME_FIELD}
BUFFITEM.is_extendable = false
BUFFITEM.extensions = {}

BuffItem = protobuf.Message(BUFFITEM)

