-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Buff_pb')


BUFF = protobuf.Descriptor();
local BUFF_BUFFID_FIELD = protobuf.FieldDescriptor();
local BUFF_BUFFLEVEL_FIELD = protobuf.FieldDescriptor();
local BUFF_EFFECTTIME_FIELD = protobuf.FieldDescriptor();
local BUFF_SKILLID_FIELD = protobuf.FieldDescriptor();

BUFF_BUFFID_FIELD.name = "buffID"
BUFF_BUFFID_FIELD.full_name = ".KKSG.Buff.buffID"
BUFF_BUFFID_FIELD.number = 1
BUFF_BUFFID_FIELD.index = 0
BUFF_BUFFID_FIELD.label = 1
BUFF_BUFFID_FIELD.has_default_value = false
BUFF_BUFFID_FIELD.default_value = 0
BUFF_BUFFID_FIELD.type = 5
BUFF_BUFFID_FIELD.cpp_type = 1

BUFF_BUFFLEVEL_FIELD.name = "buffLevel"
BUFF_BUFFLEVEL_FIELD.full_name = ".KKSG.Buff.buffLevel"
BUFF_BUFFLEVEL_FIELD.number = 2
BUFF_BUFFLEVEL_FIELD.index = 1
BUFF_BUFFLEVEL_FIELD.label = 1
BUFF_BUFFLEVEL_FIELD.has_default_value = false
BUFF_BUFFLEVEL_FIELD.default_value = 0
BUFF_BUFFLEVEL_FIELD.type = 5
BUFF_BUFFLEVEL_FIELD.cpp_type = 1

BUFF_EFFECTTIME_FIELD.name = "effecttime"
BUFF_EFFECTTIME_FIELD.full_name = ".KKSG.Buff.effecttime"
BUFF_EFFECTTIME_FIELD.number = 3
BUFF_EFFECTTIME_FIELD.index = 2
BUFF_EFFECTTIME_FIELD.label = 1
BUFF_EFFECTTIME_FIELD.has_default_value = false
BUFF_EFFECTTIME_FIELD.default_value = 0
BUFF_EFFECTTIME_FIELD.type = 13
BUFF_EFFECTTIME_FIELD.cpp_type = 3

BUFF_SKILLID_FIELD.name = "skillID"
BUFF_SKILLID_FIELD.full_name = ".KKSG.Buff.skillID"
BUFF_SKILLID_FIELD.number = 4
BUFF_SKILLID_FIELD.index = 3
BUFF_SKILLID_FIELD.label = 1
BUFF_SKILLID_FIELD.has_default_value = false
BUFF_SKILLID_FIELD.default_value = 0
BUFF_SKILLID_FIELD.type = 13
BUFF_SKILLID_FIELD.cpp_type = 3

BUFF.name = "Buff"
BUFF.full_name = ".KKSG.Buff"
BUFF.nested_types = {}
BUFF.enum_types = {}
BUFF.fields = {BUFF_BUFFID_FIELD, BUFF_BUFFLEVEL_FIELD, BUFF_EFFECTTIME_FIELD, BUFF_SKILLID_FIELD}
BUFF.is_extendable = false
BUFF.extensions = {}

Buff = protobuf.Message(BUFF)

