-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('CampTaskInfo_pb')


CAMPTASKINFO = protobuf.Descriptor();
local CAMPTASKINFO_TASKID_FIELD = protobuf.FieldDescriptor();
local CAMPTASKINFO_TASKSTATUS_FIELD = protobuf.FieldDescriptor();

CAMPTASKINFO_TASKID_FIELD.name = "taskID"
CAMPTASKINFO_TASKID_FIELD.full_name = ".KKSG.CampTaskInfo.taskID"
CAMPTASKINFO_TASKID_FIELD.number = 1
CAMPTASKINFO_TASKID_FIELD.index = 0
CAMPTASKINFO_TASKID_FIELD.label = 1
CAMPTASKINFO_TASKID_FIELD.has_default_value = false
CAMPTASKINFO_TASKID_FIELD.default_value = 0
CAMPTASKINFO_TASKID_FIELD.type = 13
CAMPTASKINFO_TASKID_FIELD.cpp_type = 3

CAMPTASKINFO_TASKSTATUS_FIELD.name = "taskStatus"
CAMPTASKINFO_TASKSTATUS_FIELD.full_name = ".KKSG.CampTaskInfo.taskStatus"
CAMPTASKINFO_TASKSTATUS_FIELD.number = 2
CAMPTASKINFO_TASKSTATUS_FIELD.index = 1
CAMPTASKINFO_TASKSTATUS_FIELD.label = 1
CAMPTASKINFO_TASKSTATUS_FIELD.has_default_value = false
CAMPTASKINFO_TASKSTATUS_FIELD.default_value = 0
CAMPTASKINFO_TASKSTATUS_FIELD.type = 5
CAMPTASKINFO_TASKSTATUS_FIELD.cpp_type = 1

CAMPTASKINFO.name = "CampTaskInfo"
CAMPTASKINFO.full_name = ".KKSG.CampTaskInfo"
CAMPTASKINFO.nested_types = {}
CAMPTASKINFO.enum_types = {}
CAMPTASKINFO.fields = {CAMPTASKINFO_TASKID_FIELD, CAMPTASKINFO_TASKSTATUS_FIELD}
CAMPTASKINFO.is_extendable = false
CAMPTASKINFO.extensions = {}

CampTaskInfo = protobuf.Message(CAMPTASKINFO)

