-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('DelayInfo_pb')


DELAYINFO = protobuf.Descriptor();
local DELAYINFO_DELAY_FIELD = protobuf.FieldDescriptor();

DELAYINFO_DELAY_FIELD.name = "delay"
DELAYINFO_DELAY_FIELD.full_name = ".KKSG.DelayInfo.delay"
DELAYINFO_DELAY_FIELD.number = 1
DELAYINFO_DELAY_FIELD.index = 0
DELAYINFO_DELAY_FIELD.label = 1
DELAYINFO_DELAY_FIELD.has_default_value = false
DELAYINFO_DELAY_FIELD.default_value = 0
DELAYINFO_DELAY_FIELD.type = 13
DELAYINFO_DELAY_FIELD.cpp_type = 3

DELAYINFO.name = "DelayInfo"
DELAYINFO.full_name = ".KKSG.DelayInfo"
DELAYINFO.nested_types = {}
DELAYINFO.enum_types = {}
DELAYINFO.fields = {DELAYINFO_DELAY_FIELD}
DELAYINFO.is_extendable = false
DELAYINFO.extensions = {}

DelayInfo = protobuf.Message(DELAYINFO)

