-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('DEProgressArg_pb')


DEPROGRESSARG = protobuf.Descriptor();

DEPROGRESSARG.name = "DEProgressArg"
DEPROGRESSARG.full_name = ".KKSG.DEProgressArg"
DEPROGRESSARG.nested_types = {}
DEPROGRESSARG.enum_types = {}
DEPROGRESSARG.fields = {}
DEPROGRESSARG.is_extendable = false
DEPROGRESSARG.extensions = {}

DEProgressArg = protobuf.Message(DEPROGRESSARG)

