-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('DneRecord_pb')


DNERECORD = protobuf.Descriptor();
local DNERECORD_DNEID_FIELD = protobuf.FieldDescriptor();
local DNERECORD_COUNT_FIELD = protobuf.FieldDescriptor();

DNERECORD_DNEID_FIELD.name = "dneid"
DNERECORD_DNEID_FIELD.full_name = ".KKSG.DneRecord.dneid"
DNERECORD_DNEID_FIELD.number = 1
DNERECORD_DNEID_FIELD.index = 0
DNERECORD_DNEID_FIELD.label = 1
DNERECORD_DNEID_FIELD.has_default_value = false
DNERECORD_DNEID_FIELD.default_value = 0
DNERECORD_DNEID_FIELD.type = 13
DNERECORD_DNEID_FIELD.cpp_type = 3

DNERECORD_COUNT_FIELD.name = "count"
DNERECORD_COUNT_FIELD.full_name = ".KKSG.DneRecord.count"
DNERECORD_COUNT_FIELD.number = 2
DNERECORD_COUNT_FIELD.index = 1
DNERECORD_COUNT_FIELD.label = 1
DNERECORD_COUNT_FIELD.has_default_value = false
DNERECORD_COUNT_FIELD.default_value = 0
DNERECORD_COUNT_FIELD.type = 13
DNERECORD_COUNT_FIELD.cpp_type = 3

DNERECORD.name = "DneRecord"
DNERECORD.full_name = ".KKSG.DneRecord"
DNERECORD.nested_types = {}
DNERECORD.enum_types = {}
DNERECORD.fields = {DNERECORD_DNEID_FIELD, DNERECORD_COUNT_FIELD}
DNERECORD.is_extendable = false
DNERECORD.extensions = {}

DneRecord = protobuf.Message(DNERECORD)

