-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('DoEnterSceneArg_pb')


DOENTERSCENEARG = protobuf.Descriptor();
local DOENTERSCENEARG_SCENEID_FIELD = protobuf.FieldDescriptor();

DOENTERSCENEARG_SCENEID_FIELD.name = "sceneid"
DOENTERSCENEARG_SCENEID_FIELD.full_name = ".KKSG.DoEnterSceneArg.sceneid"
DOENTERSCENEARG_SCENEID_FIELD.number = 1
DOENTERSCENEARG_SCENEID_FIELD.index = 0
DOENTERSCENEARG_SCENEID_FIELD.label = 1
DOENTERSCENEARG_SCENEID_FIELD.has_default_value = false
DOENTERSCENEARG_SCENEID_FIELD.default_value = 0
DOENTERSCENEARG_SCENEID_FIELD.type = 13
DOENTERSCENEARG_SCENEID_FIELD.cpp_type = 3

DOENTERSCENEARG.name = "DoEnterSceneArg"
DOENTERSCENEARG.full_name = ".KKSG.DoEnterSceneArg"
DOENTERSCENEARG.nested_types = {}
DOENTERSCENEARG.enum_types = {}
DOENTERSCENEARG.fields = {DOENTERSCENEARG_SCENEID_FIELD}
DOENTERSCENEARG.is_extendable = false
DOENTERSCENEARG.extensions = {}

DoEnterSceneArg = protobuf.Message(DOENTERSCENEARG)

