-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local FRIENDOPTYPE_PB = require("FriendOpType_pb")
module('FriendQueryReportNew_pb')


FRIENDQUERYREPORTNEW = protobuf.Descriptor();
local FRIENDQUERYREPORTNEW_OP_FIELD = protobuf.FieldDescriptor();

FRIENDQUERYREPORTNEW_OP_FIELD.name = "op"
FRIENDQUERYREPORTNEW_OP_FIELD.full_name = ".KKSG.FriendQueryReportNew.op"
FRIENDQUERYREPORTNEW_OP_FIELD.number = 1
FRIENDQUERYREPORTNEW_OP_FIELD.index = 0
FRIENDQUERYREPORTNEW_OP_FIELD.label = 1
FRIENDQUERYREPORTNEW_OP_FIELD.has_default_value = false
FRIENDQUERYREPORTNEW_OP_FIELD.default_value = nil
FRIENDQUERYREPORTNEW_OP_FIELD.enum_type = FRIENDOPTYPE_PB.FRIENDOPTYPE
FRIENDQUERYREPORTNEW_OP_FIELD.type = 14
FRIENDQUERYREPORTNEW_OP_FIELD.cpp_type = 8

FRIENDQUERYREPORTNEW.name = "FriendQueryReportNew"
FRIENDQUERYREPORTNEW.full_name = ".KKSG.FriendQueryReportNew"
FRIENDQUERYREPORTNEW.nested_types = {}
FRIENDQUERYREPORTNEW.enum_types = {}
FRIENDQUERYREPORTNEW.fields = {FRIENDQUERYREPORTNEW_OP_FIELD}
FRIENDQUERYREPORTNEW.is_extendable = false
FRIENDQUERYREPORTNEW.extensions = {}

FriendQueryReportNew = protobuf.Message(FRIENDQUERYREPORTNEW)

