-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetDragonTopInfoArg_pb')


GETDRAGONTOPINFOARG = protobuf.Descriptor();

GETDRAGONTOPINFOARG.name = "GetDragonTopInfoArg"
GETDRAGONTOPINFOARG.full_name = ".KKSG.GetDragonTopInfoArg"
GETDRAGONTOPINFOARG.nested_types = {}
GETDRAGONTOPINFOARG.enum_types = {}
GETDRAGONTOPINFOARG.fields = {}
GETDRAGONTOPINFOARG.is_extendable = false
GETDRAGONTOPINFOARG.extensions = {}

GetDragonTopInfoArg = protobuf.Message(GETDRAGONTOPINFOARG)

