-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetDailyTaskInfoArg_pb')


GETDAILYTASKINFOARG = protobuf.Descriptor();

GETDAILYTASKINFOARG.name = "GetDailyTaskInfoArg"
GETDAILYTASKINFOARG.full_name = ".KKSG.GetDailyTaskInfoArg"
GETDAILYTASKINFOARG.nested_types = {}
GETDAILYTASKINFOARG.enum_types = {}
GETDAILYTASKINFOARG.fields = {}
GETDAILYTASKINFOARG.is_extendable = false
GETDAILYTASKINFOARG.extensions = {}

GetDailyTaskInfoArg = protobuf.Message(GETDAILYTASKINFOARG)

