-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetHolidayStageInfoArg_pb')


GETHOLIDAYSTAGEINFOARG = protobuf.Descriptor();

GETHOLIDAYSTAGEINFOARG.name = "GetHolidayStageInfoArg"
GETHOLIDAYSTAGEINFOARG.full_name = ".KKSG.GetHolidayStageInfoArg"
GETHOLIDAYSTAGEINFOARG.nested_types = {}
GETHOLIDAYSTAGEINFOARG.enum_types = {}
GETHOLIDAYSTAGEINFOARG.fields = {}
GETHOLIDAYSTAGEINFOARG.is_extendable = false
GETHOLIDAYSTAGEINFOARG.extensions = {}

GetHolidayStageInfoArg = protobuf.Message(GETHOLIDAYSTAGEINFOARG)

