-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetMobaBattleInfoArg_pb')


GETMOBABATTLEINFOARG = protobuf.Descriptor();

GETMOBABATTLEINFOARG.name = "GetMobaBattleInfoArg"
GETMOBABATTLEINFOARG.full_name = ".KKSG.GetMobaBattleInfoArg"
GETMOBABATTLEINFOARG.nested_types = {}
GETMOBABATTLEINFOARG.enum_types = {}
GETMOBABATTLEINFOARG.fields = {}
GETMOBABATTLEINFOARG.is_extendable = false
GETMOBABATTLEINFOARG.extensions = {}

GetMobaBattleInfoArg = protobuf.Message(GETMOBABATTLEINFOARG)

