-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetPartnerInfoArg_pb')


GETPARTNERINFOARG = protobuf.Descriptor();

GETPARTNERINFOARG.name = "GetPartnerInfoArg"
GETPARTNERINFOARG.full_name = ".KKSG.GetPartnerInfoArg"
GETPARTNERINFOARG.nested_types = {}
GETPARTNERINFOARG.enum_types = {}
GETPARTNERINFOARG.fields = {}
GETPARTNERINFOARG.is_extendable = false
GETPARTNERINFOARG.extensions = {}

GetPartnerInfoArg = protobuf.Message(GETPARTNERINFOARG)

