-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetTowerActivityTopArg_pb')


GETTOWERACTIVITYTOPARG = protobuf.Descriptor();

GETTOWERACTIVITYTOPARG.name = "GetTowerActivityTopArg"
GETTOWERACTIVITYTOPARG.full_name = ".KKSG.GetTowerActivityTopArg"
GETTOWERACTIVITYTOPARG.nested_types = {}
GETTOWERACTIVITYTOPARG.enum_types = {}
GETTOWERACTIVITYTOPARG.fields = {}
GETTOWERACTIVITYTOPARG.is_extendable = false
GETTOWERACTIVITYTOPARG.extensions = {}

GetTowerActivityTopArg = protobuf.Message(GETTOWERACTIVITYTOPARG)

