-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GetWeeklyTaskInfoArg_pb')


GETWEEKLYTASKINFOARG = protobuf.Descriptor();

GETWEEKLYTASKINFOARG.name = "GetWeeklyTaskInfoArg"
GETWEEKLYTASKINFOARG.full_name = ".KKSG.GetWeeklyTaskInfoArg"
GETWEEKLYTASKINFOARG.nested_types = {}
GETWEEKLYTASKINFOARG.enum_types = {}
GETWEEKLYTASKINFOARG.fields = {}
GETWEEKLYTASKINFOARG.is_extendable = false
GETWEEKLYTASKINFOARG.extensions = {}

GetWeeklyTaskInfoArg = protobuf.Message(GETWEEKLYTASKINFOARG)

