-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GuildSkill_pb')


GUILDSKILL = protobuf.Descriptor();
local GUILDSKILL_SKILLID_FIELD = protobuf.FieldDescriptor();
local GUILDSKILL_SKILLLVL_FIELD = protobuf.FieldDescriptor();

GUILDSKILL_SKILLID_FIELD.name = "skillId"
GUILDSKILL_SKILLID_FIELD.full_name = ".KKSG.GuildSkill.skillId"
GUILDSKILL_SKILLID_FIELD.number = 1
GUILDSKILL_SKILLID_FIELD.index = 0
GUILDSKILL_SKILLID_FIELD.label = 1
GUILDSKILL_SKILLID_FIELD.has_default_value = false
GUILDSKILL_SKILLID_FIELD.default_value = 0
GUILDSKILL_SKILLID_FIELD.type = 13
GUILDSKILL_SKILLID_FIELD.cpp_type = 3

GUILDSKILL_SKILLLVL_FIELD.name = "skillLvl"
GUILDSKILL_SKILLLVL_FIELD.full_name = ".KKSG.GuildSkill.skillLvl"
GUILDSKILL_SKILLLVL_FIELD.number = 2
GUILDSKILL_SKILLLVL_FIELD.index = 1
GUILDSKILL_SKILLLVL_FIELD.label = 1
GUILDSKILL_SKILLLVL_FIELD.has_default_value = false
GUILDSKILL_SKILLLVL_FIELD.default_value = 0
GUILDSKILL_SKILLLVL_FIELD.type = 13
GUILDSKILL_SKILLLVL_FIELD.cpp_type = 3

GUILDSKILL.name = "GuildSkill"
GUILDSKILL.full_name = ".KKSG.GuildSkill"
GUILDSKILL.nested_types = {}
GUILDSKILL.enum_types = {}
GUILDSKILL.fields = {GUILDSKILL_SKILLID_FIELD, GUILDSKILL_SKILLLVL_FIELD}
GUILDSKILL.is_extendable = false
GUILDSKILL.extensions = {}

GuildSkill = protobuf.Message(GUILDSKILL)

