-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('IBGiftOrder_pb')


IBGIFTORDER = protobuf.Descriptor();
local IBGIFTORDER_ORDERID_FIELD = protobuf.FieldDescriptor();
local IBGIFTORDER_TIME_FIELD = protobuf.FieldDescriptor();

IBGIFTORDER_ORDERID_FIELD.name = "orderid"
IBGIFTORDER_ORDERID_FIELD.full_name = ".KKSG.IBGiftOrder.orderid"
IBGIFTORDER_ORDERID_FIELD.number = 1
IBGIFTORDER_ORDERID_FIELD.index = 0
IBGIFTORDER_ORDERID_FIELD.label = 1
IBGIFTORDER_ORDERID_FIELD.has_default_value = false
IBGIFTORDER_ORDERID_FIELD.default_value = ""
IBGIFTORDER_ORDERID_FIELD.type = 9
IBGIFTORDER_ORDERID_FIELD.cpp_type = 9

IBGIFTORDER_TIME_FIELD.name = "time"
IBGIFTORDER_TIME_FIELD.full_name = ".KKSG.IBGiftOrder.time"
IBGIFTORDER_TIME_FIELD.number = 2
IBGIFTORDER_TIME_FIELD.index = 1
IBGIFTORDER_TIME_FIELD.label = 1
IBGIFTORDER_TIME_FIELD.has_default_value = false
IBGIFTORDER_TIME_FIELD.default_value = 0
IBGIFTORDER_TIME_FIELD.type = 13
IBGIFTORDER_TIME_FIELD.cpp_type = 3

IBGIFTORDER.name = "IBGiftOrder"
IBGIFTORDER.full_name = ".KKSG.IBGiftOrder"
IBGIFTORDER.nested_types = {}
IBGIFTORDER.enum_types = {}
IBGIFTORDER.fields = {IBGIFTORDER_ORDERID_FIELD, IBGIFTORDER_TIME_FIELD}
IBGIFTORDER.is_extendable = false
IBGIFTORDER.extensions = {}

IBGiftOrder = protobuf.Message(IBGIFTORDER)

