-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('IdipMessage_pb')


IDIPMESSAGE = protobuf.Descriptor();
local IDIPMESSAGE_MESSAGE_FIELD = protobuf.FieldDescriptor();

IDIPMESSAGE_MESSAGE_FIELD.name = "message"
IDIPMESSAGE_MESSAGE_FIELD.full_name = ".KKSG.IdipMessage.message"
IDIPMESSAGE_MESSAGE_FIELD.number = 1
IDIPMESSAGE_MESSAGE_FIELD.index = 0
IDIPMESSAGE_MESSAGE_FIELD.label = 1
IDIPMESSAGE_MESSAGE_FIELD.has_default_value = false
IDIPMESSAGE_MESSAGE_FIELD.default_value = ""
IDIPMESSAGE_MESSAGE_FIELD.type = 9
IDIPMESSAGE_MESSAGE_FIELD.cpp_type = 9

IDIPMESSAGE.name = "IdipMessage"
IDIPMESSAGE.full_name = ".KKSG.IdipMessage"
IDIPMESSAGE.nested_types = {}
IDIPMESSAGE.enum_types = {}
IDIPMESSAGE.fields = {IDIPMESSAGE_MESSAGE_FIELD}
IDIPMESSAGE.is_extendable = false
IDIPMESSAGE.extensions = {}

IdipMessage = protobuf.Message(IDIPMESSAGE)

