-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('IdipHintData_pb')


IDIPHINTDATA = protobuf.Descriptor();
local IDIPHINTDATA_SYSTEMID_FIELD = protobuf.FieldDescriptor();
local IDIPHINTDATA_ISHINT_FIELD = protobuf.FieldDescriptor();

IDIPHINTDATA_SYSTEMID_FIELD.name = "systemid"
IDIPHINTDATA_SYSTEMID_FIELD.full_name = ".KKSG.IdipHintData.systemid"
IDIPHINTDATA_SYSTEMID_FIELD.number = 1
IDIPHINTDATA_SYSTEMID_FIELD.index = 0
IDIPHINTDATA_SYSTEMID_FIELD.label = 1
IDIPHINTDATA_SYSTEMID_FIELD.has_default_value = false
IDIPHINTDATA_SYSTEMID_FIELD.default_value = 0
IDIPHINTDATA_SYSTEMID_FIELD.type = 13
IDIPHINTDATA_SYSTEMID_FIELD.cpp_type = 3

IDIPHINTDATA_ISHINT_FIELD.name = "ishint"
IDIPHINTDATA_ISHINT_FIELD.full_name = ".KKSG.IdipHintData.ishint"
IDIPHINTDATA_ISHINT_FIELD.number = 2
IDIPHINTDATA_ISHINT_FIELD.index = 1
IDIPHINTDATA_ISHINT_FIELD.label = 1
IDIPHINTDATA_ISHINT_FIELD.has_default_value = false
IDIPHINTDATA_ISHINT_FIELD.default_value = false
IDIPHINTDATA_ISHINT_FIELD.type = 8
IDIPHINTDATA_ISHINT_FIELD.cpp_type = 7

IDIPHINTDATA.name = "IdipHintData"
IDIPHINTDATA.full_name = ".KKSG.IdipHintData"
IDIPHINTDATA.nested_types = {}
IDIPHINTDATA.enum_types = {}
IDIPHINTDATA.fields = {IDIPHINTDATA_SYSTEMID_FIELD, IDIPHINTDATA_ISHINT_FIELD}
IDIPHINTDATA.is_extendable = false
IDIPHINTDATA.extensions = {}

IdipHintData = protobuf.Message(IDIPHINTDATA)

