-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ItemBrief_pb')


ITEMBRIEF = protobuf.Descriptor();
local ITEMBRIEF_ITEMID_FIELD = protobuf.FieldDescriptor();
local ITEMBRIEF_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
local ITEMBRIEF_ISBIND_FIELD = protobuf.FieldDescriptor();
local ITEMBRIEF_COOLDOWN_FIELD = protobuf.FieldDescriptor();

ITEMBRIEF_ITEMID_FIELD.name = "itemID"
ITEMBRIEF_ITEMID_FIELD.full_name = ".KKSG.ItemBrief.itemID"
ITEMBRIEF_ITEMID_FIELD.number = 1
ITEMBRIEF_ITEMID_FIELD.index = 0
ITEMBRIEF_ITEMID_FIELD.label = 1
ITEMBRIEF_ITEMID_FIELD.has_default_value = false
ITEMBRIEF_ITEMID_FIELD.default_value = 0
ITEMBRIEF_ITEMID_FIELD.type = 13
ITEMBRIEF_ITEMID_FIELD.cpp_type = 3

ITEMBRIEF_ITEMCOUNT_FIELD.name = "itemCount"
ITEMBRIEF_ITEMCOUNT_FIELD.full_name = ".KKSG.ItemBrief.itemCount"
ITEMBRIEF_ITEMCOUNT_FIELD.number = 2
ITEMBRIEF_ITEMCOUNT_FIELD.index = 1
ITEMBRIEF_ITEMCOUNT_FIELD.label = 1
ITEMBRIEF_ITEMCOUNT_FIELD.has_default_value = false
ITEMBRIEF_ITEMCOUNT_FIELD.default_value = 0
ITEMBRIEF_ITEMCOUNT_FIELD.type = 13
ITEMBRIEF_ITEMCOUNT_FIELD.cpp_type = 3

ITEMBRIEF_ISBIND_FIELD.name = "isbind"
ITEMBRIEF_ISBIND_FIELD.full_name = ".KKSG.ItemBrief.isbind"
ITEMBRIEF_ISBIND_FIELD.number = 3
ITEMBRIEF_ISBIND_FIELD.index = 2
ITEMBRIEF_ISBIND_FIELD.label = 1
ITEMBRIEF_ISBIND_FIELD.has_default_value = false
ITEMBRIEF_ISBIND_FIELD.default_value = false
ITEMBRIEF_ISBIND_FIELD.type = 8
ITEMBRIEF_ISBIND_FIELD.cpp_type = 7

ITEMBRIEF_COOLDOWN_FIELD.name = "cooldown"
ITEMBRIEF_COOLDOWN_FIELD.full_name = ".KKSG.ItemBrief.cooldown"
ITEMBRIEF_COOLDOWN_FIELD.number = 4
ITEMBRIEF_COOLDOWN_FIELD.index = 3
ITEMBRIEF_COOLDOWN_FIELD.label = 1
ITEMBRIEF_COOLDOWN_FIELD.has_default_value = false
ITEMBRIEF_COOLDOWN_FIELD.default_value = 0
ITEMBRIEF_COOLDOWN_FIELD.type = 13
ITEMBRIEF_COOLDOWN_FIELD.cpp_type = 3

ITEMBRIEF.name = "ItemBrief"
ITEMBRIEF.full_name = ".KKSG.ItemBrief"
ITEMBRIEF.nested_types = {}
ITEMBRIEF.enum_types = {}
ITEMBRIEF.fields = {ITEMBRIEF_ITEMID_FIELD, ITEMBRIEF_ITEMCOUNT_FIELD, ITEMBRIEF_ISBIND_FIELD, ITEMBRIEF_COOLDOWN_FIELD}
ITEMBRIEF.is_extendable = false
ITEMBRIEF.extensions = {}

ItemBrief = protobuf.Message(ITEMBRIEF)

