-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ItemFuse_pb')


ITEMFUSE = protobuf.Descriptor();
local ITEMFUSE_FUSELEVEL_FIELD = protobuf.FieldDescriptor();
local ITEMFUSE_FUSEEXPCOUNT_FIELD = protobuf.FieldDescriptor();

ITEMFUSE_FUSELEVEL_FIELD.name = "fuseLevel"
ITEMFUSE_FUSELEVEL_FIELD.full_name = ".KKSG.ItemFuse.fuseLevel"
ITEMFUSE_FUSELEVEL_FIELD.number = 1
ITEMFUSE_FUSELEVEL_FIELD.index = 0
ITEMFUSE_FUSELEVEL_FIELD.label = 1
ITEMFUSE_FUSELEVEL_FIELD.has_default_value = false
ITEMFUSE_FUSELEVEL_FIELD.default_value = 0
ITEMFUSE_FUSELEVEL_FIELD.type = 13
ITEMFUSE_FUSELEVEL_FIELD.cpp_type = 3

ITEMFUSE_FUSEEXPCOUNT_FIELD.name = "fuseExpCount"
ITEMFUSE_FUSEEXPCOUNT_FIELD.full_name = ".KKSG.ItemFuse.fuseExpCount"
ITEMFUSE_FUSEEXPCOUNT_FIELD.number = 2
ITEMFUSE_FUSEEXPCOUNT_FIELD.index = 1
ITEMFUSE_FUSEEXPCOUNT_FIELD.label = 1
ITEMFUSE_FUSEEXPCOUNT_FIELD.has_default_value = false
ITEMFUSE_FUSEEXPCOUNT_FIELD.default_value = 0
ITEMFUSE_FUSEEXPCOUNT_FIELD.type = 13
ITEMFUSE_FUSEEXPCOUNT_FIELD.cpp_type = 3

ITEMFUSE.name = "ItemFuse"
ITEMFUSE.full_name = ".KKSG.ItemFuse"
ITEMFUSE.nested_types = {}
ITEMFUSE.enum_types = {}
ITEMFUSE.fields = {ITEMFUSE_FUSELEVEL_FIELD, ITEMFUSE_FUSEEXPCOUNT_FIELD}
ITEMFUSE.is_extendable = false
ITEMFUSE.extensions = {}

ItemFuse = protobuf.Message(ITEMFUSE)

