-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ITEMJADESINGLE_PB = require("ItemJadeSingle_pb")
module('ItemJade_pb')


ITEMJADE = protobuf.Descriptor();
local ITEMJADE_SLOTINFO_FIELD = protobuf.FieldDescriptor();
local ITEMJADE_ITEMJADESINGLE_FIELD = protobuf.FieldDescriptor();

ITEMJADE_SLOTINFO_FIELD.name = "SlotInfo"
ITEMJADE_SLOTINFO_FIELD.full_name = ".KKSG.ItemJade.SlotInfo"
ITEMJADE_SLOTINFO_FIELD.number = 1
ITEMJADE_SLOTINFO_FIELD.index = 0
ITEMJADE_SLOTINFO_FIELD.label = 1
ITEMJADE_SLOTINFO_FIELD.has_default_value = false
ITEMJADE_SLOTINFO_FIELD.default_value = 0
ITEMJADE_SLOTINFO_FIELD.type = 13
ITEMJADE_SLOTINFO_FIELD.cpp_type = 3

ITEMJADE_ITEMJADESINGLE_FIELD.name = "ItemJadeSingle"
ITEMJADE_ITEMJADESINGLE_FIELD.full_name = ".KKSG.ItemJade.ItemJadeSingle"
ITEMJADE_ITEMJADESINGLE_FIELD.number = 2
ITEMJADE_ITEMJADESINGLE_FIELD.index = 1
ITEMJADE_ITEMJADESINGLE_FIELD.label = 3
ITEMJADE_ITEMJADESINGLE_FIELD.has_default_value = false
ITEMJADE_ITEMJADESINGLE_FIELD.default_value = {}
ITEMJADE_ITEMJADESINGLE_FIELD.message_type = ITEMJADESINGLE_PB.ITEMJADESINGLE
ITEMJADE_ITEMJADESINGLE_FIELD.type = 11
ITEMJADE_ITEMJADESINGLE_FIELD.cpp_type = 10

ITEMJADE.name = "ItemJade"
ITEMJADE.full_name = ".KKSG.ItemJade"
ITEMJADE.nested_types = {}
ITEMJADE.enum_types = {}
ITEMJADE.fields = {ITEMJADE_SLOTINFO_FIELD, ITEMJADE_ITEMJADESINGLE_FIELD}
ITEMJADE.is_extendable = false
ITEMJADE.extensions = {}

ItemJade = protobuf.Message(ITEMJADE)

