-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ENUM_PB = require("Enum_pb")
local ITEMBRIEF_PB = require("ItemBrief_pb")
module('LoginReward_pb')


LOGINREWARD = protobuf.Descriptor();
local LOGINREWARD_DAY_FIELD = protobuf.FieldDescriptor();
local LOGINREWARD_ITEMID_FIELD = protobuf.FieldDescriptor();
local LOGINREWARD_STATE_FIELD = protobuf.FieldDescriptor();
local LOGINREWARD_ITEMS_FIELD = protobuf.FieldDescriptor();

LOGINREWARD_DAY_FIELD.name = "day"
LOGINREWARD_DAY_FIELD.full_name = ".KKSG.LoginReward.day"
LOGINREWARD_DAY_FIELD.number = 1
LOGINREWARD_DAY_FIELD.index = 0
LOGINREWARD_DAY_FIELD.label = 1
LOGINREWARD_DAY_FIELD.has_default_value = false
LOGINREWARD_DAY_FIELD.default_value = 0
LOGINREWARD_DAY_FIELD.type = 5
LOGINREWARD_DAY_FIELD.cpp_type = 1

LOGINREWARD_ITEMID_FIELD.name = "itemID"
LOGINREWARD_ITEMID_FIELD.full_name = ".KKSG.LoginReward.itemID"
LOGINREWARD_ITEMID_FIELD.number = 2
LOGINREWARD_ITEMID_FIELD.index = 1
LOGINREWARD_ITEMID_FIELD.label = 1
LOGINREWARD_ITEMID_FIELD.has_default_value = false
LOGINREWARD_ITEMID_FIELD.default_value = 0
LOGINREWARD_ITEMID_FIELD.type = 13
LOGINREWARD_ITEMID_FIELD.cpp_type = 3

LOGINREWARD_STATE_FIELD.name = "state"
LOGINREWARD_STATE_FIELD.full_name = ".KKSG.LoginReward.state"
LOGINREWARD_STATE_FIELD.number = 3
LOGINREWARD_STATE_FIELD.index = 2
LOGINREWARD_STATE_FIELD.label = 1
LOGINREWARD_STATE_FIELD.has_default_value = false
LOGINREWARD_STATE_FIELD.default_value = nil
LOGINREWARD_STATE_FIELD.enum_type = ENUM_PB.LOGINREWARDSTATE
LOGINREWARD_STATE_FIELD.type = 14
LOGINREWARD_STATE_FIELD.cpp_type = 8

LOGINREWARD_ITEMS_FIELD.name = "items"
LOGINREWARD_ITEMS_FIELD.full_name = ".KKSG.LoginReward.items"
LOGINREWARD_ITEMS_FIELD.number = 4
LOGINREWARD_ITEMS_FIELD.index = 3
LOGINREWARD_ITEMS_FIELD.label = 3
LOGINREWARD_ITEMS_FIELD.has_default_value = false
LOGINREWARD_ITEMS_FIELD.default_value = {}
LOGINREWARD_ITEMS_FIELD.message_type = ITEMBRIEF_PB.ITEMBRIEF
LOGINREWARD_ITEMS_FIELD.type = 11
LOGINREWARD_ITEMS_FIELD.cpp_type = 10

LOGINREWARD.name = "LoginReward"
LOGINREWARD.full_name = ".KKSG.LoginReward"
LOGINREWARD.nested_types = {}
LOGINREWARD.enum_types = {}
LOGINREWARD.fields = {LOGINREWARD_DAY_FIELD, LOGINREWARD_ITEMID_FIELD, LOGINREWARD_STATE_FIELD, LOGINREWARD_ITEMS_FIELD}
LOGINREWARD.is_extendable = false
LOGINREWARD.extensions = {}

LoginReward = protobuf.Message(LOGINREWARD)

