-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('MapIntItem_pb')


MAPINTITEM = protobuf.Descriptor();
local MAPINTITEM_KEY_FIELD = protobuf.FieldDescriptor();
local MAPINTITEM_VALUE_FIELD = protobuf.FieldDescriptor();

MAPINTITEM_KEY_FIELD.name = "key"
MAPINTITEM_KEY_FIELD.full_name = ".KKSG.MapIntItem.key"
MAPINTITEM_KEY_FIELD.number = 1
MAPINTITEM_KEY_FIELD.index = 0
MAPINTITEM_KEY_FIELD.label = 1
MAPINTITEM_KEY_FIELD.has_default_value = false
MAPINTITEM_KEY_FIELD.default_value = 0
MAPINTITEM_KEY_FIELD.type = 4
MAPINTITEM_KEY_FIELD.cpp_type = 4

MAPINTITEM_VALUE_FIELD.name = "value"
MAPINTITEM_VALUE_FIELD.full_name = ".KKSG.MapIntItem.value"
MAPINTITEM_VALUE_FIELD.number = 2
MAPINTITEM_VALUE_FIELD.index = 1
MAPINTITEM_VALUE_FIELD.label = 1
MAPINTITEM_VALUE_FIELD.has_default_value = false
MAPINTITEM_VALUE_FIELD.default_value = 0
MAPINTITEM_VALUE_FIELD.type = 13
MAPINTITEM_VALUE_FIELD.cpp_type = 3

MAPINTITEM.name = "MapIntItem"
MAPINTITEM.full_name = ".KKSG.MapIntItem"
MAPINTITEM.nested_types = {}
MAPINTITEM.enum_types = {}
MAPINTITEM.fields = {MAPINTITEM_KEY_FIELD, MAPINTITEM_VALUE_FIELD}
MAPINTITEM.is_extendable = false
MAPINTITEM.extensions = {}

MapIntItem = protobuf.Message(MAPINTITEM)

