-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('NpcFeelingUnite_pb')


NPCFEELINGUNITE = protobuf.Descriptor();
local NPCFEELINGUNITE_ID_FIELD = protobuf.FieldDescriptor();
local NPCFEELINGUNITE_LEVEL_FIELD = protobuf.FieldDescriptor();

NPCFEELINGUNITE_ID_FIELD.name = "id"
NPCFEELINGUNITE_ID_FIELD.full_name = ".KKSG.NpcFeelingUnite.id"
NPCFEELINGUNITE_ID_FIELD.number = 1
NPCFEELINGUNITE_ID_FIELD.index = 0
NPCFEELINGUNITE_ID_FIELD.label = 1
NPCFEELINGUNITE_ID_FIELD.has_default_value = false
NPCFEELINGUNITE_ID_FIELD.default_value = 0
NPCFEELINGUNITE_ID_FIELD.type = 13
NPCFEELINGUNITE_ID_FIELD.cpp_type = 3

NPCFEELINGUNITE_LEVEL_FIELD.name = "level"
NPCFEELINGUNITE_LEVEL_FIELD.full_name = ".KKSG.NpcFeelingUnite.level"
NPCFEELINGUNITE_LEVEL_FIELD.number = 2
NPCFEELINGUNITE_LEVEL_FIELD.index = 1
NPCFEELINGUNITE_LEVEL_FIELD.label = 1
NPCFEELINGUNITE_LEVEL_FIELD.has_default_value = false
NPCFEELINGUNITE_LEVEL_FIELD.default_value = 0
NPCFEELINGUNITE_LEVEL_FIELD.type = 13
NPCFEELINGUNITE_LEVEL_FIELD.cpp_type = 3

NPCFEELINGUNITE.name = "NpcFeelingUnite"
NPCFEELINGUNITE.full_name = ".KKSG.NpcFeelingUnite"
NPCFEELINGUNITE.nested_types = {}
NPCFEELINGUNITE.enum_types = {}
NPCFEELINGUNITE.fields = {NPCFEELINGUNITE_ID_FIELD, NPCFEELINGUNITE_LEVEL_FIELD}
NPCFEELINGUNITE.is_extendable = false
NPCFEELINGUNITE.extensions = {}

NpcFeelingUnite = protobuf.Message(NPCFEELINGUNITE)

