-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('PayBaseInfo_pb')


PAYBASEINFO = protobuf.Descriptor();
local PAYBASEINFO_PARAMID_FIELD = protobuf.FieldDescriptor();
local PAYBASEINFO_ISPAY_FIELD = protobuf.FieldDescriptor();

PAYBASEINFO_PARAMID_FIELD.name = "paramID"
PAYBASEINFO_PARAMID_FIELD.full_name = ".KKSG.PayBaseInfo.paramID"
PAYBASEINFO_PARAMID_FIELD.number = 1
PAYBASEINFO_PARAMID_FIELD.index = 0
PAYBASEINFO_PARAMID_FIELD.label = 1
PAYBASEINFO_PARAMID_FIELD.has_default_value = false
PAYBASEINFO_PARAMID_FIELD.default_value = ""
PAYBASEINFO_PARAMID_FIELD.type = 9
PAYBASEINFO_PARAMID_FIELD.cpp_type = 9

PAYBASEINFO_ISPAY_FIELD.name = "isPay"
PAYBASEINFO_ISPAY_FIELD.full_name = ".KKSG.PayBaseInfo.isPay"
PAYBASEINFO_ISPAY_FIELD.number = 2
PAYBASEINFO_ISPAY_FIELD.index = 1
PAYBASEINFO_ISPAY_FIELD.label = 1
PAYBASEINFO_ISPAY_FIELD.has_default_value = false
PAYBASEINFO_ISPAY_FIELD.default_value = false
PAYBASEINFO_ISPAY_FIELD.type = 8
PAYBASEINFO_ISPAY_FIELD.cpp_type = 7

PAYBASEINFO.name = "PayBaseInfo"
PAYBASEINFO.full_name = ".KKSG.PayBaseInfo"
PAYBASEINFO.nested_types = {}
PAYBASEINFO.enum_types = {}
PAYBASEINFO.fields = {PAYBASEINFO_PARAMID_FIELD, PAYBASEINFO_ISPAY_FIELD}
PAYBASEINFO.is_extendable = false
PAYBASEINFO.extensions = {}

PayBaseInfo = protobuf.Message(PAYBASEINFO)

