-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('PayconsumeBrief_pb')


PAYCONSUMEBRIEF = protobuf.Descriptor();
local PAYCONSUMEBRIEF_TS_FIELD = protobuf.FieldDescriptor();
local PAYCONSUMEBRIEF_BILLNO_FIELD = protobuf.FieldDescriptor();

PAYCONSUMEBRIEF_TS_FIELD.name = "ts"
PAYCONSUMEBRIEF_TS_FIELD.full_name = ".KKSG.PayconsumeBrief.ts"
PAYCONSUMEBRIEF_TS_FIELD.number = 1
PAYCONSUMEBRIEF_TS_FIELD.index = 0
PAYCONSUMEBRIEF_TS_FIELD.label = 1
PAYCONSUMEBRIEF_TS_FIELD.has_default_value = false
PAYCONSUMEBRIEF_TS_FIELD.default_value = 0
PAYCONSUMEBRIEF_TS_FIELD.type = 13
PAYCONSUMEBRIEF_TS_FIELD.cpp_type = 3

PAYCONSUMEBRIEF_BILLNO_FIELD.name = "billno"
PAYCONSUMEBRIEF_BILLNO_FIELD.full_name = ".KKSG.PayconsumeBrief.billno"
PAYCONSUMEBRIEF_BILLNO_FIELD.number = 2
PAYCONSUMEBRIEF_BILLNO_FIELD.index = 1
PAYCONSUMEBRIEF_BILLNO_FIELD.label = 1
PAYCONSUMEBRIEF_BILLNO_FIELD.has_default_value = false
PAYCONSUMEBRIEF_BILLNO_FIELD.default_value = ""
PAYCONSUMEBRIEF_BILLNO_FIELD.type = 9
PAYCONSUMEBRIEF_BILLNO_FIELD.cpp_type = 9

PAYCONSUMEBRIEF.name = "PayconsumeBrief"
PAYCONSUMEBRIEF.full_name = ".KKSG.PayconsumeBrief"
PAYCONSUMEBRIEF.nested_types = {}
PAYCONSUMEBRIEF.enum_types = {}
PAYCONSUMEBRIEF.fields = {PAYCONSUMEBRIEF_TS_FIELD, PAYCONSUMEBRIEF_BILLNO_FIELD}
PAYCONSUMEBRIEF.is_extendable = false
PAYCONSUMEBRIEF.extensions = {}

PayconsumeBrief = protobuf.Message(PAYCONSUMEBRIEF)

