-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('PlatType_pb')


local PLATTYPE = protobuf.EnumDescriptor();
local PLATTYPE_PLAT_IOS_ENUM = protobuf.EnumValueDescriptor();
local PLATTYPE_PLAT_ANDROID_ENUM = protobuf.EnumValueDescriptor();

PLATTYPE_PLAT_IOS_ENUM.name = "PLAT_IOS"
PLATTYPE_PLAT_IOS_ENUM.index = 0
PLATTYPE_PLAT_IOS_ENUM.number = 0
PLATTYPE_PLAT_ANDROID_ENUM.name = "PLAT_ANDROID"
PLATTYPE_PLAT_ANDROID_ENUM.index = 1
PLATTYPE_PLAT_ANDROID_ENUM.number = 1
PLATTYPE.name = "PlatType"
PLATTYPE.full_name = ".KKSG.PlatType"
PLATTYPE.values = {PLATTYPE_PLAT_IOS_ENUM,PLATTYPE_PLAT_ANDROID_ENUM}

PLAT_ANDROID = 1
PLAT_IOS = 0

