-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('PushInfo_pb')


PUSHINFO = protobuf.Descriptor();
local PUSHINFO_TYPE_FIELD = protobuf.FieldDescriptor();
local PUSHINFO_SUB_TYPE_FIELD = protobuf.FieldDescriptor();
local PUSHINFO_TIME_FIELD = protobuf.FieldDescriptor();

PUSHINFO_TYPE_FIELD.name = "type"
PUSHINFO_TYPE_FIELD.full_name = ".KKSG.PushInfo.type"
PUSHINFO_TYPE_FIELD.number = 1
PUSHINFO_TYPE_FIELD.index = 0
PUSHINFO_TYPE_FIELD.label = 1
PUSHINFO_TYPE_FIELD.has_default_value = false
PUSHINFO_TYPE_FIELD.default_value = 0
PUSHINFO_TYPE_FIELD.type = 13
PUSHINFO_TYPE_FIELD.cpp_type = 3

PUSHINFO_SUB_TYPE_FIELD.name = "sub_type"
PUSHINFO_SUB_TYPE_FIELD.full_name = ".KKSG.PushInfo.sub_type"
PUSHINFO_SUB_TYPE_FIELD.number = 2
PUSHINFO_SUB_TYPE_FIELD.index = 1
PUSHINFO_SUB_TYPE_FIELD.label = 1
PUSHINFO_SUB_TYPE_FIELD.has_default_value = false
PUSHINFO_SUB_TYPE_FIELD.default_value = 0
PUSHINFO_SUB_TYPE_FIELD.type = 13
PUSHINFO_SUB_TYPE_FIELD.cpp_type = 3

PUSHINFO_TIME_FIELD.name = "time"
PUSHINFO_TIME_FIELD.full_name = ".KKSG.PushInfo.time"
PUSHINFO_TIME_FIELD.number = 3
PUSHINFO_TIME_FIELD.index = 2
PUSHINFO_TIME_FIELD.label = 1
PUSHINFO_TIME_FIELD.has_default_value = false
PUSHINFO_TIME_FIELD.default_value = 0
PUSHINFO_TIME_FIELD.type = 13
PUSHINFO_TIME_FIELD.cpp_type = 3

PUSHINFO.name = "PushInfo"
PUSHINFO.full_name = ".KKSG.PushInfo"
PUSHINFO.nested_types = {}
PUSHINFO.enum_types = {}
PUSHINFO.fields = {PUSHINFO_TYPE_FIELD, PUSHINFO_SUB_TYPE_FIELD, PUSHINFO_TIME_FIELD}
PUSHINFO.is_extendable = false
PUSHINFO.extensions = {}

PushInfo = protobuf.Message(PUSHINFO)

