-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('PushConfig_pb')


PUSHCONFIG = protobuf.Descriptor();
local PUSHCONFIG_TYPE_FIELD = protobuf.FieldDescriptor();
local PUSHCONFIG_FORBID_FIELD = protobuf.FieldDescriptor();

PUSHCONFIG_TYPE_FIELD.name = "type"
PUSHCONFIG_TYPE_FIELD.full_name = ".KKSG.PushConfig.type"
PUSHCONFIG_TYPE_FIELD.number = 1
PUSHCONFIG_TYPE_FIELD.index = 0
PUSHCONFIG_TYPE_FIELD.label = 1
PUSHCONFIG_TYPE_FIELD.has_default_value = false
PUSHCONFIG_TYPE_FIELD.default_value = 0
PUSHCONFIG_TYPE_FIELD.type = 13
PUSHCONFIG_TYPE_FIELD.cpp_type = 3

PUSHCONFIG_FORBID_FIELD.name = "forbid"
PUSHCONFIG_FORBID_FIELD.full_name = ".KKSG.PushConfig.forbid"
PUSHCONFIG_FORBID_FIELD.number = 2
PUSHCONFIG_FORBID_FIELD.index = 1
PUSHCONFIG_FORBID_FIELD.label = 1
PUSHCONFIG_FORBID_FIELD.has_default_value = false
PUSHCONFIG_FORBID_FIELD.default_value = false
PUSHCONFIG_FORBID_FIELD.type = 8
PUSHCONFIG_FORBID_FIELD.cpp_type = 7

PUSHCONFIG.name = "PushConfig"
PUSHCONFIG.full_name = ".KKSG.PushConfig"
PUSHCONFIG.nested_types = {}
PUSHCONFIG.enum_types = {}
PUSHCONFIG.fields = {PUSHCONFIG_TYPE_FIELD, PUSHCONFIG_FORBID_FIELD}
PUSHCONFIG.is_extendable = false
PUSHCONFIG.extensions = {}

PushConfig = protobuf.Message(PUSHCONFIG)

