-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local PVPREQTYPE_PB = require("PvpReqType_pb")
module('PvpArg_pb')


PVPARG = protobuf.Descriptor();
local PVPARG_TYPE_FIELD = protobuf.FieldDescriptor();

PVPARG_TYPE_FIELD.name = "type"
PVPARG_TYPE_FIELD.full_name = ".KKSG.PvpArg.type"
PVPARG_TYPE_FIELD.number = 1
PVPARG_TYPE_FIELD.index = 0
PVPARG_TYPE_FIELD.label = 1
PVPARG_TYPE_FIELD.has_default_value = false
PVPARG_TYPE_FIELD.default_value = nil
PVPARG_TYPE_FIELD.enum_type = PVPREQTYPE_PB.PVPREQTYPE
PVPARG_TYPE_FIELD.type = 14
PVPARG_TYPE_FIELD.cpp_type = 8

PVPARG.name = "PvpArg"
PVPARG.full_name = ".KKSG.PvpArg"
PVPARG.nested_types = {}
PVPARG.enum_types = {}
PVPARG.fields = {PVPARG_TYPE_FIELD}
PVPARG.is_extendable = false
PVPARG.extensions = {}

PvpArg = protobuf.Message(PVPARG)

