-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local PVPONEREC_PB = require("PvpOneRec_pb")
module('PvpHistory_pb')


PVPHISTORY = protobuf.Descriptor();
local PVPHISTORY_RECS_FIELD = protobuf.FieldDescriptor();

PVPHISTORY_RECS_FIELD.name = "recs"
PVPHISTORY_RECS_FIELD.full_name = ".KKSG.PvpHistory.recs"
PVPHISTORY_RECS_FIELD.number = 1
PVPHISTORY_RECS_FIELD.index = 0
PVPHISTORY_RECS_FIELD.label = 3
PVPHISTORY_RECS_FIELD.has_default_value = false
PVPHISTORY_RECS_FIELD.default_value = {}
PVPHISTORY_RECS_FIELD.message_type = PVPONEREC_PB.PVPONEREC
PVPHISTORY_RECS_FIELD.type = 11
PVPHISTORY_RECS_FIELD.cpp_type = 10

PVPHISTORY.name = "PvpHistory"
PVPHISTORY.full_name = ".KKSG.PvpHistory"
PVPHISTORY.nested_types = {}
PVPHISTORY.enum_types = {}
PVPHISTORY.fields = {PVPHISTORY_RECS_FIELD}
PVPHISTORY.is_extendable = false
PVPHISTORY.extensions = {}

PvpHistory = protobuf.Message(PVPHISTORY)

