-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('QueryGuildCardArg_pb')


QUERYGUILDCARDARG = protobuf.Descriptor();

QUERYGUILDCARDARG.name = "QueryGuildCardArg"
QUERYGUILDCARDARG.full_name = ".KKSG.QueryGuildCardArg"
QUERYGUILDCARDARG.nested_types = {}
QUERYGUILDCARDARG.enum_types = {}
QUERYGUILDCARDARG.fields = {}
QUERYGUILDCARDARG.is_extendable = false
QUERYGUILDCARDARG.extensions = {}

QueryGuildCardArg = protobuf.Message(QUERYGUILDCARDARG)

