-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('QueryPowerPointArg_pb')


QUERYPOWERPOINTARG = protobuf.Descriptor();

QUERYPOWERPOINTARG.name = "QueryPowerPointArg"
QUERYPOWERPOINTARG.full_name = ".KKSG.QueryPowerPointArg"
QUERYPOWERPOINTARG.nested_types = {}
QUERYPOWERPOINTARG.enum_types = {}
QUERYPOWERPOINTARG.fields = {}
QUERYPOWERPOINTARG.is_extendable = false
QUERYPOWERPOINTARG.extensions = {}

QueryPowerPointArg = protobuf.Message(QUERYPOWERPOINTARG)

