-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('QueryClientIpRes_pb')


QUERYCLIENTIPRES = protobuf.Descriptor();
local QUERYCLIENTIPRES_IP_FIELD = protobuf.FieldDescriptor();

QUERYCLIENTIPRES_IP_FIELD.name = "ip"
QUERYCLIENTIPRES_IP_FIELD.full_name = ".KKSG.QueryClientIpRes.ip"
QUERYCLIENTIPRES_IP_FIELD.number = 1
QUERYCLIENTIPRES_IP_FIELD.index = 0
QUERYCLIENTIPRES_IP_FIELD.label = 1
QUERYCLIENTIPRES_IP_FIELD.has_default_value = false
QUERYCLIENTIPRES_IP_FIELD.default_value = ""
QUERYCLIENTIPRES_IP_FIELD.type = 9
QUERYCLIENTIPRES_IP_FIELD.cpp_type = 9

QUERYCLIENTIPRES.name = "QueryClientIpRes"
QUERYCLIENTIPRES.full_name = ".KKSG.QueryClientIpRes"
QUERYCLIENTIPRES.nested_types = {}
QUERYCLIENTIPRES.enum_types = {}
QUERYCLIENTIPRES.fields = {QUERYCLIENTIPRES_IP_FIELD}
QUERYCLIENTIPRES.is_extendable = false
QUERYCLIENTIPRES.extensions = {}

QueryClientIpRes = protobuf.Message(QUERYCLIENTIPRES)

