-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ReconnArg_pb')


RECONNARG = protobuf.Descriptor();
local RECONNARG_SESSION_FIELD = protobuf.FieldDescriptor();
local RECONNARG_SCENEID_FIELD = protobuf.FieldDescriptor();
local RECONNARG_ROLEID_FIELD = protobuf.FieldDescriptor();

RECONNARG_SESSION_FIELD.name = "session"
RECONNARG_SESSION_FIELD.full_name = ".KKSG.ReconnArg.session"
RECONNARG_SESSION_FIELD.number = 1
RECONNARG_SESSION_FIELD.index = 0
RECONNARG_SESSION_FIELD.label = 1
RECONNARG_SESSION_FIELD.has_default_value = false
RECONNARG_SESSION_FIELD.default_value = 0
RECONNARG_SESSION_FIELD.type = 4
RECONNARG_SESSION_FIELD.cpp_type = 4

RECONNARG_SCENEID_FIELD.name = "sceneid"
RECONNARG_SCENEID_FIELD.full_name = ".KKSG.ReconnArg.sceneid"
RECONNARG_SCENEID_FIELD.number = 2
RECONNARG_SCENEID_FIELD.index = 1
RECONNARG_SCENEID_FIELD.label = 1
RECONNARG_SCENEID_FIELD.has_default_value = false
RECONNARG_SCENEID_FIELD.default_value = 0
RECONNARG_SCENEID_FIELD.type = 13
RECONNARG_SCENEID_FIELD.cpp_type = 3

RECONNARG_ROLEID_FIELD.name = "roleid"
RECONNARG_ROLEID_FIELD.full_name = ".KKSG.ReconnArg.roleid"
RECONNARG_ROLEID_FIELD.number = 3
RECONNARG_ROLEID_FIELD.index = 2
RECONNARG_ROLEID_FIELD.label = 1
RECONNARG_ROLEID_FIELD.has_default_value = false
RECONNARG_ROLEID_FIELD.default_value = 0
RECONNARG_ROLEID_FIELD.type = 4
RECONNARG_ROLEID_FIELD.cpp_type = 4

RECONNARG.name = "ReconnArg"
RECONNARG.full_name = ".KKSG.ReconnArg"
RECONNARG.nested_types = {}
RECONNARG.enum_types = {}
RECONNARG.fields = {RECONNARG_SESSION_FIELD, RECONNARG_SCENEID_FIELD, RECONNARG_ROLEID_FIELD}
RECONNARG.is_extendable = false
RECONNARG.extensions = {}

ReconnArg = protobuf.Message(RECONNARG)

