-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ATLASDATA_PB = require("atlasdata_pb")
module('SAtlasRecord_pb')


SATLASRECORD = protobuf.Descriptor();
local SATLASRECORD_ATLAS_FIELD = protobuf.FieldDescriptor();
local SATLASRECORD_FINISHDATA_FIELD = protobuf.FieldDescriptor();

SATLASRECORD_ATLAS_FIELD.name = "atlas"
SATLASRECORD_ATLAS_FIELD.full_name = ".KKSG.SAtlasRecord.atlas"
SATLASRECORD_ATLAS_FIELD.number = 1
SATLASRECORD_ATLAS_FIELD.index = 0
SATLASRECORD_ATLAS_FIELD.label = 3
SATLASRECORD_ATLAS_FIELD.has_default_value = false
SATLASRECORD_ATLAS_FIELD.default_value = {}
SATLASRECORD_ATLAS_FIELD.type = 13
SATLASRECORD_ATLAS_FIELD.cpp_type = 3

SATLASRECORD_FINISHDATA_FIELD.name = "finishdata"
SATLASRECORD_FINISHDATA_FIELD.full_name = ".KKSG.SAtlasRecord.finishdata"
SATLASRECORD_FINISHDATA_FIELD.number = 2
SATLASRECORD_FINISHDATA_FIELD.index = 1
SATLASRECORD_FINISHDATA_FIELD.label = 3
SATLASRECORD_FINISHDATA_FIELD.has_default_value = false
SATLASRECORD_FINISHDATA_FIELD.default_value = {}
SATLASRECORD_FINISHDATA_FIELD.message_type = ATLASDATA_PB.ATLASDATA
SATLASRECORD_FINISHDATA_FIELD.type = 11
SATLASRECORD_FINISHDATA_FIELD.cpp_type = 10

SATLASRECORD.name = "SAtlasRecord"
SATLASRECORD.full_name = ".KKSG.SAtlasRecord"
SATLASRECORD.nested_types = {}
SATLASRECORD.enum_types = {}
SATLASRECORD.fields = {SATLASRECORD_ATLAS_FIELD, SATLASRECORD_FINISHDATA_FIELD}
SATLASRECORD.is_extendable = false
SATLASRECORD.extensions = {}

SAtlasRecord = protobuf.Message(SATLASRECORD)

