-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ERRORCODE_PB = require("ErrorCode_pb")
module('SetRoleConfigRes_pb')


SETROLECONFIGRES = protobuf.Descriptor();
local SETROLECONFIGRES_ERRORCODE_FIELD = protobuf.FieldDescriptor();

SETROLECONFIGRES_ERRORCODE_FIELD.name = "errorcode"
SETROLECONFIGRES_ERRORCODE_FIELD.full_name = ".KKSG.SetRoleConfigRes.errorcode"
SETROLECONFIGRES_ERRORCODE_FIELD.number = 1
SETROLECONFIGRES_ERRORCODE_FIELD.index = 0
SETROLECONFIGRES_ERRORCODE_FIELD.label = 1
SETROLECONFIGRES_ERRORCODE_FIELD.has_default_value = false
SETROLECONFIGRES_ERRORCODE_FIELD.default_value = nil
SETROLECONFIGRES_ERRORCODE_FIELD.enum_type = ERRORCODE_PB.ERRORCODE
SETROLECONFIGRES_ERRORCODE_FIELD.type = 14
SETROLECONFIGRES_ERRORCODE_FIELD.cpp_type = 8

SETROLECONFIGRES.name = "SetRoleConfigRes"
SETROLECONFIGRES.full_name = ".KKSG.SetRoleConfigRes"
SETROLECONFIGRES.nested_types = {}
SETROLECONFIGRES.enum_types = {}
SETROLECONFIGRES.fields = {SETROLECONFIGRES_ERRORCODE_FIELD}
SETROLECONFIGRES.is_extendable = false
SETROLECONFIGRES.extensions = {}

SetRoleConfigRes = protobuf.Message(SETROLECONFIGRES)

