-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local ITEM_PB = require("Item_pb")
module('ShopItem_pb')


SHOPITEM = protobuf.Descriptor();
local SHOPITEM_ITEM_FIELD = protobuf.FieldDescriptor();
local SHOPITEM_SLOT_FIELD = protobuf.FieldDescriptor();
local SHOPITEM_BUYCOUNT_FIELD = protobuf.FieldDescriptor();
local SHOPITEM_DAILYBUYCOUNT_FIELD = protobuf.FieldDescriptor();
local SHOPITEM_WEEKBUYCOUNT_FIELD = protobuf.FieldDescriptor();

SHOPITEM_ITEM_FIELD.name = "Item"
SHOPITEM_ITEM_FIELD.full_name = ".KKSG.ShopItem.Item"
SHOPITEM_ITEM_FIELD.number = 1
SHOPITEM_ITEM_FIELD.index = 0
SHOPITEM_ITEM_FIELD.label = 1
SHOPITEM_ITEM_FIELD.has_default_value = false
SHOPITEM_ITEM_FIELD.default_value = nil
SHOPITEM_ITEM_FIELD.message_type = ITEM_PB.ITEM
SHOPITEM_ITEM_FIELD.type = 11
SHOPITEM_ITEM_FIELD.cpp_type = 10

SHOPITEM_SLOT_FIELD.name = "slot"
SHOPITEM_SLOT_FIELD.full_name = ".KKSG.ShopItem.slot"
SHOPITEM_SLOT_FIELD.number = 2
SHOPITEM_SLOT_FIELD.index = 1
SHOPITEM_SLOT_FIELD.label = 1
SHOPITEM_SLOT_FIELD.has_default_value = false
SHOPITEM_SLOT_FIELD.default_value = 0
SHOPITEM_SLOT_FIELD.type = 13
SHOPITEM_SLOT_FIELD.cpp_type = 3

SHOPITEM_BUYCOUNT_FIELD.name = "buycount"
SHOPITEM_BUYCOUNT_FIELD.full_name = ".KKSG.ShopItem.buycount"
SHOPITEM_BUYCOUNT_FIELD.number = 3
SHOPITEM_BUYCOUNT_FIELD.index = 2
SHOPITEM_BUYCOUNT_FIELD.label = 1
SHOPITEM_BUYCOUNT_FIELD.has_default_value = false
SHOPITEM_BUYCOUNT_FIELD.default_value = 0
SHOPITEM_BUYCOUNT_FIELD.type = 13
SHOPITEM_BUYCOUNT_FIELD.cpp_type = 3

SHOPITEM_DAILYBUYCOUNT_FIELD.name = "dailybuycount"
SHOPITEM_DAILYBUYCOUNT_FIELD.full_name = ".KKSG.ShopItem.dailybuycount"
SHOPITEM_DAILYBUYCOUNT_FIELD.number = 4
SHOPITEM_DAILYBUYCOUNT_FIELD.index = 3
SHOPITEM_DAILYBUYCOUNT_FIELD.label = 1
SHOPITEM_DAILYBUYCOUNT_FIELD.has_default_value = false
SHOPITEM_DAILYBUYCOUNT_FIELD.default_value = 0
SHOPITEM_DAILYBUYCOUNT_FIELD.type = 13
SHOPITEM_DAILYBUYCOUNT_FIELD.cpp_type = 3

SHOPITEM_WEEKBUYCOUNT_FIELD.name = "weekbuycount"
SHOPITEM_WEEKBUYCOUNT_FIELD.full_name = ".KKSG.ShopItem.weekbuycount"
SHOPITEM_WEEKBUYCOUNT_FIELD.number = 5
SHOPITEM_WEEKBUYCOUNT_FIELD.index = 4
SHOPITEM_WEEKBUYCOUNT_FIELD.label = 1
SHOPITEM_WEEKBUYCOUNT_FIELD.has_default_value = false
SHOPITEM_WEEKBUYCOUNT_FIELD.default_value = 0
SHOPITEM_WEEKBUYCOUNT_FIELD.type = 13
SHOPITEM_WEEKBUYCOUNT_FIELD.cpp_type = 3

SHOPITEM.name = "ShopItem"
SHOPITEM.full_name = ".KKSG.ShopItem"
SHOPITEM.nested_types = {}
SHOPITEM.enum_types = {}
SHOPITEM.fields = {SHOPITEM_ITEM_FIELD, SHOPITEM_SLOT_FIELD, SHOPITEM_BUYCOUNT_FIELD, SHOPITEM_DAILYBUYCOUNT_FIELD, SHOPITEM_WEEKBUYCOUNT_FIELD}
SHOPITEM.is_extendable = false
SHOPITEM.extensions = {}

ShopItem = protobuf.Message(SHOPITEM)

