-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('SSceneState_pb')


SSCENESTATE = protobuf.Descriptor();
local SSCENESTATE_ISREADY_FIELD = protobuf.FieldDescriptor();
local SSCENESTATE_RUNSTATE_FIELD = protobuf.FieldDescriptor();

SSCENESTATE_ISREADY_FIELD.name = "isready"
SSCENESTATE_ISREADY_FIELD.full_name = ".KKSG.SSceneState.isready"
SSCENESTATE_ISREADY_FIELD.number = 1
SSCENESTATE_ISREADY_FIELD.index = 0
SSCENESTATE_ISREADY_FIELD.label = 1
SSCENESTATE_ISREADY_FIELD.has_default_value = false
SSCENESTATE_ISREADY_FIELD.default_value = false
SSCENESTATE_ISREADY_FIELD.type = 8
SSCENESTATE_ISREADY_FIELD.cpp_type = 7

SSCENESTATE_RUNSTATE_FIELD.name = "runstate"
SSCENESTATE_RUNSTATE_FIELD.full_name = ".KKSG.SSceneState.runstate"
SSCENESTATE_RUNSTATE_FIELD.number = 2
SSCENESTATE_RUNSTATE_FIELD.index = 1
SSCENESTATE_RUNSTATE_FIELD.label = 1
SSCENESTATE_RUNSTATE_FIELD.has_default_value = false
SSCENESTATE_RUNSTATE_FIELD.default_value = 0
SSCENESTATE_RUNSTATE_FIELD.type = 13
SSCENESTATE_RUNSTATE_FIELD.cpp_type = 3

SSCENESTATE.name = "SSceneState"
SSCENESTATE.full_name = ".KKSG.SSceneState"
SSCENESTATE.nested_types = {}
SSCENESTATE.enum_types = {}
SSCENESTATE.fields = {SSCENESTATE_ISREADY_FIELD, SSCENESTATE_RUNSTATE_FIELD}
SSCENESTATE.is_extendable = false
SSCENESTATE.extensions = {}

SSceneState = protobuf.Message(SSCENESTATE)

