-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('StageAssistOne_pb')


STAGEASSISTONE = protobuf.Descriptor();
local STAGEASSISTONE_STAGEID_FIELD = protobuf.FieldDescriptor();
local STAGEASSISTONE_POINT_FIELD = protobuf.FieldDescriptor();

STAGEASSISTONE_STAGEID_FIELD.name = "stageid"
STAGEASSISTONE_STAGEID_FIELD.full_name = ".KKSG.StageAssistOne.stageid"
STAGEASSISTONE_STAGEID_FIELD.number = 1
STAGEASSISTONE_STAGEID_FIELD.index = 0
STAGEASSISTONE_STAGEID_FIELD.label = 1
STAGEASSISTONE_STAGEID_FIELD.has_default_value = false
STAGEASSISTONE_STAGEID_FIELD.default_value = 0
STAGEASSISTONE_STAGEID_FIELD.type = 13
STAGEASSISTONE_STAGEID_FIELD.cpp_type = 3

STAGEASSISTONE_POINT_FIELD.name = "point"
STAGEASSISTONE_POINT_FIELD.full_name = ".KKSG.StageAssistOne.point"
STAGEASSISTONE_POINT_FIELD.number = 2
STAGEASSISTONE_POINT_FIELD.index = 1
STAGEASSISTONE_POINT_FIELD.label = 1
STAGEASSISTONE_POINT_FIELD.has_default_value = false
STAGEASSISTONE_POINT_FIELD.default_value = 0
STAGEASSISTONE_POINT_FIELD.type = 5
STAGEASSISTONE_POINT_FIELD.cpp_type = 1

STAGEASSISTONE.name = "StageAssistOne"
STAGEASSISTONE.full_name = ".KKSG.StageAssistOne"
STAGEASSISTONE.nested_types = {}
STAGEASSISTONE.enum_types = {}
STAGEASSISTONE.fields = {STAGEASSISTONE_STAGEID_FIELD, STAGEASSISTONE_POINT_FIELD}
STAGEASSISTONE.is_extendable = false
STAGEASSISTONE.extensions = {}

StageAssistOne = protobuf.Message(STAGEASSISTONE)

