-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Systems_pb')


SYSTEMS = protobuf.Descriptor();
local SYSTEMS_SYSIDS_FIELD = protobuf.FieldDescriptor();
local SYSTEMS_CLOSESYSIDS_FIELD = protobuf.FieldDescriptor();

SYSTEMS_SYSIDS_FIELD.name = "sysIDs"
SYSTEMS_SYSIDS_FIELD.full_name = ".KKSG.Systems.sysIDs"
SYSTEMS_SYSIDS_FIELD.number = 1
SYSTEMS_SYSIDS_FIELD.index = 0
SYSTEMS_SYSIDS_FIELD.label = 3
SYSTEMS_SYSIDS_FIELD.has_default_value = false
SYSTEMS_SYSIDS_FIELD.default_value = {}
SYSTEMS_SYSIDS_FIELD.type = 13
SYSTEMS_SYSIDS_FIELD.cpp_type = 3

SYSTEMS_CLOSESYSIDS_FIELD.name = "closeSysIDs"
SYSTEMS_CLOSESYSIDS_FIELD.full_name = ".KKSG.Systems.closeSysIDs"
SYSTEMS_CLOSESYSIDS_FIELD.number = 2
SYSTEMS_CLOSESYSIDS_FIELD.index = 1
SYSTEMS_CLOSESYSIDS_FIELD.label = 3
SYSTEMS_CLOSESYSIDS_FIELD.has_default_value = false
SYSTEMS_CLOSESYSIDS_FIELD.default_value = {}
SYSTEMS_CLOSESYSIDS_FIELD.type = 13
SYSTEMS_CLOSESYSIDS_FIELD.cpp_type = 3

SYSTEMS.name = "Systems"
SYSTEMS.full_name = ".KKSG.Systems"
SYSTEMS.nested_types = {}
SYSTEMS.enum_types = {}
SYSTEMS.fields = {SYSTEMS_SYSIDS_FIELD, SYSTEMS_CLOSESYSIDS_FIELD}
SYSTEMS.is_extendable = false
SYSTEMS.extensions = {}

Systems = protobuf.Message(SYSTEMS)

