-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local TASKCONDITIONINFO_PB = require("TaskConditionInfo_pb")
local ENUM_PB = require("Enum_pb")
module('TaskInfo_pb')


TASKINFO = protobuf.Descriptor();
local TASKINFO_ID_FIELD = protobuf.FieldDescriptor();
local TASKINFO_STATUS_FIELD = protobuf.FieldDescriptor();
local TASKINFO_CONDS_FIELD = protobuf.FieldDescriptor();

TASKINFO_ID_FIELD.name = "id"
TASKINFO_ID_FIELD.full_name = ".KKSG.TaskInfo.id"
TASKINFO_ID_FIELD.number = 1
TASKINFO_ID_FIELD.index = 0
TASKINFO_ID_FIELD.label = 1
TASKINFO_ID_FIELD.has_default_value = false
TASKINFO_ID_FIELD.default_value = 0
TASKINFO_ID_FIELD.type = 13
TASKINFO_ID_FIELD.cpp_type = 3

TASKINFO_STATUS_FIELD.name = "status"
TASKINFO_STATUS_FIELD.full_name = ".KKSG.TaskInfo.status"
TASKINFO_STATUS_FIELD.number = 2
TASKINFO_STATUS_FIELD.index = 1
TASKINFO_STATUS_FIELD.label = 1
TASKINFO_STATUS_FIELD.has_default_value = false
TASKINFO_STATUS_FIELD.default_value = nil
TASKINFO_STATUS_FIELD.enum_type = ENUM_PB.TASKSTATUS
TASKINFO_STATUS_FIELD.type = 14
TASKINFO_STATUS_FIELD.cpp_type = 8

TASKINFO_CONDS_FIELD.name = "conds"
TASKINFO_CONDS_FIELD.full_name = ".KKSG.TaskInfo.conds"
TASKINFO_CONDS_FIELD.number = 3
TASKINFO_CONDS_FIELD.index = 2
TASKINFO_CONDS_FIELD.label = 3
TASKINFO_CONDS_FIELD.has_default_value = false
TASKINFO_CONDS_FIELD.default_value = {}
TASKINFO_CONDS_FIELD.message_type = TASKCONDITIONINFO_PB.TASKCONDITIONINFO
TASKINFO_CONDS_FIELD.type = 11
TASKINFO_CONDS_FIELD.cpp_type = 10

TASKINFO.name = "TaskInfo"
TASKINFO.full_name = ".KKSG.TaskInfo"
TASKINFO.nested_types = {}
TASKINFO.enum_types = {}
TASKINFO.fields = {TASKINFO_ID_FIELD, TASKINFO_STATUS_FIELD, TASKINFO_CONDS_FIELD}
TASKINFO.is_extendable = false
TASKINFO.extensions = {}

TaskInfo = protobuf.Message(TASKINFO)

