-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('TrophyDetail_pb')


TROPHYDETAIL = protobuf.Descriptor();
local TROPHYDETAIL_TROPY_ORDER_FIELD = protobuf.FieldDescriptor();
local TROPHYDETAIL_TROPHY_TIME_FIELD = protobuf.FieldDescriptor();

TROPHYDETAIL_TROPY_ORDER_FIELD.name = "tropy_order"
TROPHYDETAIL_TROPY_ORDER_FIELD.full_name = ".KKSG.TrophyDetail.tropy_order"
TROPHYDETAIL_TROPY_ORDER_FIELD.number = 1
TROPHYDETAIL_TROPY_ORDER_FIELD.index = 0
TROPHYDETAIL_TROPY_ORDER_FIELD.label = 1
TROPHYDETAIL_TROPY_ORDER_FIELD.has_default_value = false
TROPHYDETAIL_TROPY_ORDER_FIELD.default_value = 0
TROPHYDETAIL_TROPY_ORDER_FIELD.type = 13
TROPHYDETAIL_TROPY_ORDER_FIELD.cpp_type = 3

TROPHYDETAIL_TROPHY_TIME_FIELD.name = "trophy_time"
TROPHYDETAIL_TROPHY_TIME_FIELD.full_name = ".KKSG.TrophyDetail.trophy_time"
TROPHYDETAIL_TROPHY_TIME_FIELD.number = 2
TROPHYDETAIL_TROPHY_TIME_FIELD.index = 1
TROPHYDETAIL_TROPHY_TIME_FIELD.label = 1
TROPHYDETAIL_TROPHY_TIME_FIELD.has_default_value = false
TROPHYDETAIL_TROPHY_TIME_FIELD.default_value = 0
TROPHYDETAIL_TROPHY_TIME_FIELD.type = 13
TROPHYDETAIL_TROPHY_TIME_FIELD.cpp_type = 3

TROPHYDETAIL.name = "TrophyDetail"
TROPHYDETAIL.full_name = ".KKSG.TrophyDetail"
TROPHYDETAIL.nested_types = {}
TROPHYDETAIL.enum_types = {}
TROPHYDETAIL.fields = {TROPHYDETAIL_TROPY_ORDER_FIELD, TROPHYDETAIL_TROPHY_TIME_FIELD}
TROPHYDETAIL.is_extendable = false
TROPHYDETAIL.extensions = {}

TrophyDetail = protobuf.Message(TROPHYDETAIL)

