-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('TutorialInfo_pb')


TUTORIALINFO = protobuf.Descriptor();
local TUTORIALINFO_TUTORIALID_FIELD = protobuf.FieldDescriptor();

TUTORIALINFO_TUTORIALID_FIELD.name = "tutorialID"
TUTORIALINFO_TUTORIALID_FIELD.full_name = ".KKSG.TutorialInfo.tutorialID"
TUTORIALINFO_TUTORIALID_FIELD.number = 1
TUTORIALINFO_TUTORIALID_FIELD.index = 0
TUTORIALINFO_TUTORIALID_FIELD.label = 1
TUTORIALINFO_TUTORIALID_FIELD.has_default_value = false
TUTORIALINFO_TUTORIALID_FIELD.default_value = 0
TUTORIALINFO_TUTORIALID_FIELD.type = 13
TUTORIALINFO_TUTORIALID_FIELD.cpp_type = 3

TUTORIALINFO.name = "TutorialInfo"
TUTORIALINFO.full_name = ".KKSG.TutorialInfo"
TUTORIALINFO.nested_types = {}
TUTORIALINFO.enum_types = {}
TUTORIALINFO.fields = {TUTORIALINFO_TUTORIALID_FIELD}
TUTORIALINFO.is_extendable = false
TUTORIALINFO.extensions = {}

TutorialInfo = protobuf.Message(TUTORIALINFO)

