-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Vec3_pb')


VEC3 = protobuf.Descriptor();
local VEC3_X_FIELD = protobuf.FieldDescriptor();
local VEC3_Y_FIELD = protobuf.FieldDescriptor();
local VEC3_Z_FIELD = protobuf.FieldDescriptor();

VEC3_X_FIELD.name = "x"
VEC3_X_FIELD.full_name = ".KKSG.Vec3.x"
VEC3_X_FIELD.number = 1
VEC3_X_FIELD.index = 0
VEC3_X_FIELD.label = 1
VEC3_X_FIELD.has_default_value = false
VEC3_X_FIELD.default_value = 0.0
VEC3_X_FIELD.type = 2
VEC3_X_FIELD.cpp_type = 6

VEC3_Y_FIELD.name = "y"
VEC3_Y_FIELD.full_name = ".KKSG.Vec3.y"
VEC3_Y_FIELD.number = 2
VEC3_Y_FIELD.index = 1
VEC3_Y_FIELD.label = 1
VEC3_Y_FIELD.has_default_value = false
VEC3_Y_FIELD.default_value = 0.0
VEC3_Y_FIELD.type = 2
VEC3_Y_FIELD.cpp_type = 6

VEC3_Z_FIELD.name = "z"
VEC3_Z_FIELD.full_name = ".KKSG.Vec3.z"
VEC3_Z_FIELD.number = 3
VEC3_Z_FIELD.index = 2
VEC3_Z_FIELD.label = 1
VEC3_Z_FIELD.has_default_value = false
VEC3_Z_FIELD.default_value = 0.0
VEC3_Z_FIELD.type = 2
VEC3_Z_FIELD.cpp_type = 6

VEC3.name = "Vec3"
VEC3.full_name = ".KKSG.Vec3"
VEC3.nested_types = {}
VEC3.enum_types = {}
VEC3.fields = {VEC3_X_FIELD, VEC3_Y_FIELD, VEC3_Z_FIELD}
VEC3.is_extendable = false
VEC3.extensions = {}

Vec3 = protobuf.Message(VEC3)

