-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('WeekEnd4v4GetInfoArg_pb')


WEEKEND4V4GETINFOARG = protobuf.Descriptor();

WEEKEND4V4GETINFOARG.name = "WeekEnd4v4GetInfoArg"
WEEKEND4V4GETINFOARG.full_name = ".KKSG.WeekEnd4v4GetInfoArg"
WEEKEND4V4GETINFOARG.nested_types = {}
WEEKEND4V4GETINFOARG.enum_types = {}
WEEKEND4V4GETINFOARG.fields = {}
WEEKEND4V4GETINFOARG.is_extendable = false
WEEKEND4V4GETINFOARG.extensions = {}

WeekEnd4v4GetInfoArg = protobuf.Message(WEEKEND4V4GETINFOARG)

